name: Sutekh CI

on:
  # Run on every push and PR
  push:
  pull_request:
  # Run a job every Subday morning so we're aware of changes to installer builds, etc.
  schedule:
    - cron: '12 4 * * 0'

jobs:
  sqlite-macos:

    # We're using the github supplied version of python here
    # and the homebrew gtk libraries - it's not quite clear
    # what the minimum supported version of MacOS is with
    # but builds on MacOS 12 currently works on MacOS 11 and
    # newer and may wotk on MacOS 10.15.
    #
    # It's possible to control the supported versions directly
    # See https://github.com/actions/virtual-environments/issues/1256#issuecomment-770270252
    # but as this will require compiling the gtk support with the
    # correct options, it doesn't seem worthwhile.
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v3
    - name: Install brew dependencies
      run: |
        brew install gtk+3 gobject-introspection librsvg adwaita-icon-theme gtk-mac-integration poppler hicolor-icon-theme
    - name: Install PIP dependencies
      run: |
        pip install keyring ply sqlobject configobj pytest mock PyGObject pycairo cx_Freeze
    - name: Build Mac packages
      run: |
        ls -l /Library/Frameworks/Python.framework/Versions/3.12/etc/openssl/cert.pem
        python3 -c 'import ssl; print(ssl.get_default_verify_paths())'
        cd sutekh
        python3 setup-freeze.py bdist_mac
        # Permissions are helpful for playing with the files in the app
        chmod 755 build/[Ss]utekh*app*/Contents/MacOS/SutekhCli* build/[Ss]utekh*app*/Contents/MacOS/SutekhGui*
        cd ..
    - name: Tar cx_Freeze app
      # We need to do this so we can preserve permissions, as the
      # github artifact upload explicitly doesn't
      run: |
        cd sutekh/build/
        tar -cf sutekh_app.tar [Ss]utekh*app*
    - name: Upload cx_Freeze app directory
      uses: actions/upload-artifact@v3
      with:
        name: sutekh-cx_Freeze_macos-app
        path: sutekh/build/sutekh_app.tar
    #- name: Build dmg file
      #run: |
        #cd sutekh
        #python3 setup-freeze.py bdist_dmg
        #cd ..
    #- name: Upload cx_Freeze dmg file
      #uses: actions/upload-artifact@v3
      #with:
        #name: sutekh-cx_Freeze_macos-dmg
        #path: sutekh/build/Sutekh*dmg

